import { API_CAE_PUBLIC_V2, API_CAE_V2, getAPI_CAE_URL } from "./API_CAE_V2";
import { API_COMUN_V2, API_COMUN_PUBLIC_V2, getAPI_COMUN_URL } from "./API_COMUN_V2";
import { API_ESTRUCTURA_V2, getAPI_ESTRUCTURA_URL } from "./API_ESTRUCTURA_V2";
export {
  API_CAE_PUBLIC_V2,
  API_CAE_V2,
  getAPI_CAE_URL,
  API_COMUN_V2,
  API_COMUN_PUBLIC_V2,
  getAPI_COMUN_URL,
  API_ESTRUCTURA_V2,
  getAPI_ESTRUCTURA_URL,
};
